version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: student_api
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_NAME=student_api
      - DB_USER=root
      - DB_PASSWORD=root@123